# Generated by Django 4.1 on 2023-07-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('ALB', models.IntegerField()),
                ('ALP', models.IntegerField()),
                ('ALT', models.IntegerField()),
                ('AST', models.IntegerField()),
                ('BIL', models.IntegerField()),
                ('CHE', models.IntegerField()),
                ('CHOL', models.IntegerField()),
                ('CREA', models.IntegerField()),
                ('GGT', models.IntegerField()),
                ('PROT', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
