# Generated by Django 4.1 on 2023-07-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ALB',
            field=models.FloatField(default=0, max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ALP',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ALT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='AST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='BIL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CHE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CHOL',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='CREA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='GGT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PROT',
            field=models.FloatField(),
        ),
    ]
